source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!


target "IdentityServer4Base" do
  
  pod 'Alamofire', '~> 4.7'

  #https://github.com/matthewpalmer/Locksmith
  pod 'Locksmith'

  pod 'MBProgressHUD'

end
